[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m pr_agent.servers.github_app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
